### PR TITLE
Make sure our base exception extends \Throwable

### PR DESCRIPTION
**Pull request by Nyholm**
As suggested by @Ocramius

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM

**Comment by sagikazarmark** [comment]
I'm not a huge fan of it for the reasons I already explained. This drops 5.x support, while all other PSRs still support it.

Also, the only gain is that you can't implement this interface, only if the class extends the base `Exception` class. Unless I'm missing something, that's rather makes the interface foolproof, but has no real benefit.

**Comment by Ocramius** [comment]
Without it being a throwable, catching this exception gives you a type gap,
since the API is not defined. Any static analysis or reflection-based tool
would be unable to work with it.

Other than that, please just stop the 5.* support: it is an already rotting
version.

**Comment by dbu** [comment]
if we drop exceptions in the PSR completely, this is a non-issue.

is there an official stand of the FIG on php 5 support for new PSR?

**Comment by kelunik** [comment]
@dbu We can't remove exceptions completely, otherwise there's no defined error handling mechanism anymore.

**Comment by Ocramius** [comment]
David, exception types being thrown should be documented and interfaced in
any decent API

**Comment by sagikazarmark** [comment]
> please just stop the 5.* support: it is an already rotting version

I agree that no more libraries should be written/major versions released with 5.x support.

But there are tons of legacy applications that still use 5.x. Rewriting these applications takes a lot of time. One step to the right direction for them can be replacing an old HTTP client (like Guzzle 3) with a standard like this.

I'm okay with implementing Throwable as long as the library includes a polyfill for the exception, providing 5.x support.

(BTW I would be the happiest person alive if PHP 5.x disappeared, but the world simply doesn't work that way)

**Comment by Ocramius** [comment]
@sagikazarmark please just stop hoping for 5.x support on *new software*. 5.x is to be considered retired, as [active support ended in january 2017](http://php.net/supported-versions.php).

New software will be written with new libraries. Old software will keep running with the old stuff.

**Comment by dbu** [comment]
yep, got confused with the exceptions. we do need to solve this question.

again, is there an official position of the FIG on whether new PSR must / must not support php 5? if the only question is whether to provide a polyfill, i don't see the problem of doing a polyfill. gradual upgrade paths of legacy codebases are a thing, and could be a valid use case why a PSR should still support 5.

**Comment by Ocramius** [comment]
@dbu a well-defined return type declaration on an interface beats all of the reasons of this world tho ;-)

**Comment by Nyholm** [comment]
I will merge this PR since we all agreed on that is the **right** thing todo. 

Let's add polyfill if we think PHP 5 support is really needed.

**Comment by clue** [comment]
-- Sorry, misread, nothing to see here.

~~<small>I understand the motivation for this change and agree that is makes sense, but what is the versioning policy here? Note that this is a BC break that will result in a fatal error if the updated version is used in a PHP 5 environment, as `Throwable` is only defined in PHP 7+.</small>~~

**Comment by Ocramius** [comment]
Christian, see
http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

**Comment by sagikazarmark** [comment]
@Ocramius I think you are missing my point.

> Old software will keep running with the old stuff.

Strongly disagree. There is no such thing as only old and only new software.

Applications are often needed to be maintained for a long time, especially when we are talking about products. You have to upgrade from time to time, either because of security policies or to get new features. I'm pretty sure I don't have to explain how to work with (near) legacy applications.

I do think this is an argument which you simply neglected.

I would be the happiest if PHP 5.x and Windows <10 just simply stopped working, but that's not how upgrade path works.

That said, I am not going to fight for this as the solution is pretty simple (polyfill).

**Comment by Ocramius** [comment]
They don't "stop working". This dependency will not automatically add
itself to your Debian 5 production servers. They keep working with their
existing set of dependencies.

**Comment by mdrost** [comment]
[`PHP classes cannot implement the Throwable interface directly, and must instead extend Exception. `](http://php.net/manual/en/class.throwable.php) so why not just extend `Exception` if user is anyway forced to extend `Exception`? Make an abstract class of this interface and it will end compatibility problems.

**Comment by Ocramius** [comment]
The problem arises when type-hinting against this interface, not when
inheriting from it. You will have to extend from a base exception anyway in
that scenario.

**Pull request merged**
